#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,6,8,19,41,43,54,56,64&i=1,2,3,4,15,16,17,28,29,30,39&v=16,5,-1,17,27,26,25,15,2,4,21 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ILI9341, OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL			DSP_ILI9341
#define TFT_DC			16
#define BRIGHTNESS_PIN			17
#define ENC_BTNR			15
#define ENC_BTNL			2
#define ENC_BTNB			4
#define SDC_CS			21
#define L10N_LANGUAGE			RU

#endif
